name: Conventional Commit Validation Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install commitlint
        run: npm install -g @commitlint/{cli,config-conventional}

      - name: Fetch latest changes
        run: git fetch origin main

      - name: Validate commits
        run: commitlint --from=origin/main --to=$GITHUB_SHA --config=commitlint.config.js
